"""Profile roster, per-profile paths, creation, and context files.

A profile is one person: their portfolio database, their broker snapshot, their
personal context files, and the Telegram id the bot routes their messages by.
The roster lives at ``$CASH_ASH_HOME/profiles.toml``; everything a profile owns
lives under ``$CASH_ASH_HOME/profiles/<name>/``.

One Telegram bot serves every profile. The token is shared infrastructure in
``.env``; the per-person part is the numeric ``telegram_id`` here, which the
daemon routes incoming updates by. Separate bots per person would mean a
BotFather registration, a token and a polling loop each, for no benefit.

Public API:
    Profile              -- one person's configuration and paths
    ProfileConfigError   -- roster missing, malformed, or inconsistent
    load_profiles        -- read and validate the whole roster
    operator_profile     -- the default profile for bare commands
    resolve_cli_profile  -- turn --profile/--db into a database path
    add_profile          -- create a profile, its directories and templates
    context_status       -- which context files exist and whether they are stubs
    CONTEXT_FILES        -- the context files a profile owns

Example:
    from profiles import resolve_cli_profile

    profile, db_path = resolve_cli_profile(args.profile, db=args.db)
"""

from __future__ import annotations

import logging
import re
import tomllib
from dataclasses import dataclass
from pathlib import Path

from config import APP_HOME, DEFAULT_MONTHLY_CONTRIBUTION_EUR

logger = logging.getLogger(__name__)

PROFILE_NAME_RE = re.compile(r"^[a-z0-9_-]+$")
PROFILES_FILE = APP_HOME / "profiles.toml"
PROFILES_DIR = APP_HOME / "profiles"

_STUB_MARKER = "<!-- cash-ash:template -->"
"""Marker written into every generated context file.

Its presence means the file is still the untouched template. ``context`` and
``doctor`` report those separately from files the user has actually written,
because an unedited strategy.md is worse than a missing one: the research
pipeline would read placeholder prose as if it were the user's intent.
"""


class ProfileConfigError(ValueError):
    """Raised when the profile roster is missing or invalid."""


@dataclass(frozen=True)
class ContextFile:
    """One personal markdown file a profile owns."""

    name: str
    title: str
    purpose: str
    generated: bool = False
    """True when CashAsh writes it rather than the user."""


CONTEXT_FILES: tuple[ContextFile, ...] = (
    ContextFile(
        "investor.md",
        "Who you are as an investor",
        "Risk tolerance, time horizon, experience, tax situation, and any hard "
        "constraints — sectors you will not hold, employer stock restrictions, "
        "money you cannot afford to lose.",
    ),
    ContextFile(
        "strategy.md",
        "What you are trying to achieve",
        "Target allocation, position sizing philosophy, what you will and will "
        "not buy, and how you decide to sell. The single most important file: "
        "it is what constrains every recommendation.",
    ),
    ContextFile(
        "log.md",
        "Your own running notes",
        "Why you bought something, what you are watching, doubts you have not "
        "acted on. Written by you, in your words, whenever you feel like it.",
    ),
    ContextFile(
        "watchlist.md",
        "Companies you are interested in but do not own",
        "Names worth researching before they are worth buying. Feeds the "
        "discovery workflow when that exists.",
    ),
    ContextFile(
        "history.md",
        "Digest of past recommendations and decisions",
        "Generated by CashAsh so each week's research knows what the last ones "
        "concluded. Do not hand-edit.",
        generated=True,
    ),
)


@dataclass(frozen=True)
class Profile:
    """One person's portfolio, files and Telegram identity."""

    name: str
    telegram_id: int
    root: Path
    operator: bool = False
    enabled: bool = True
    monthly_contribution_eur: float = DEFAULT_MONTHLY_CONTRIBUTION_EUR
    base_currency: str = "EUR"

    @property
    def db(self) -> Path:
        """This profile's portfolio database."""
        return self.root / "portfolio.db"

    @property
    def snapshot(self) -> Path:
        """This profile's broker snapshot used for seeding."""
        return self.root / "seed_snapshot.toml"

    @property
    def context(self) -> Path:
        """This profile's personal context directory."""
        return self.root / "context"

    @property
    def events_file(self) -> Path:
        """This profile's curated events file.

        Beside the snapshot rather than in ``context/`` because it is
        structured data the code parses, not prose a model reads.
        """
        return self.root / "events.toml"

    def context_path(self, name: str) -> Path:
        """Return the path of one context file."""
        return self.context / name


def validate_profile_name(name: str) -> str:
    """Validate and return a filesystem-safe profile name.

    Args:
        name: Candidate profile name.

    Returns:
        The name unchanged.

    Raises:
        ProfileConfigError: If the name is not filesystem-safe.
    """
    if not PROFILE_NAME_RE.fullmatch(name):
        raise ProfileConfigError(
            f"Invalid profile name {name!r}; use lowercase letters, digits, "
            f"'_' or '-'. It becomes a directory name."
        )
    return name


def load_profiles(path: Path = PROFILES_FILE) -> dict[str, Profile]:
    """Load and validate the complete profile roster.

    Args:
        path: Roster file to read.

    Returns:
        Profiles keyed by name.

    Raises:
        ProfileConfigError: If the roster is missing, unreadable, or invalid.
    """
    if not path.exists():
        raise ProfileConfigError(
            f"No profile roster at {path}. Create the first profile with "
            f"'uv run python main.py profile add NAME --telegram-id ID --operator'."
        )
    try:
        raw = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ProfileConfigError(
            f"Could not read profile roster {path}: {exc}"
        ) from exc

    raw_profiles = raw.get("profiles")
    if not isinstance(raw_profiles, dict) or not raw_profiles:
        raise ProfileConfigError(
            f"{path} must contain at least one [profiles.NAME] table."
        )

    roots = path.parent / "profiles"
    profiles: dict[str, Profile] = {}
    telegram_ids: set[int] = set()

    for raw_name, values in raw_profiles.items():
        name = validate_profile_name(str(raw_name))
        if not isinstance(values, dict):
            raise ProfileConfigError(f"profiles.{name} must be a TOML table.")

        telegram_id = values.get("telegram_id")
        if not isinstance(telegram_id, int) or isinstance(telegram_id, bool):
            raise ProfileConfigError(
                f"profiles.{name}.telegram_id must be an integer. Message "
                f"@userinfobot on Telegram to find it."
            )
        if telegram_id in telegram_ids:
            raise ProfileConfigError(
                f"Telegram ID {telegram_id} is assigned more than once. Each "
                f"profile needs its own, or the bot cannot tell people apart."
            )
        telegram_ids.add(telegram_id)

        operator = values.get("operator", False)
        enabled = values.get("enabled", True)
        if not isinstance(operator, bool) or not isinstance(enabled, bool):
            raise ProfileConfigError(
                f"profiles.{name}.operator and enabled must be booleans."
            )

        contribution = values.get(
            "monthly_contribution_eur", DEFAULT_MONTHLY_CONTRIBUTION_EUR
        )
        if not isinstance(contribution, int | float) or isinstance(contribution, bool):
            raise ProfileConfigError(
                f"profiles.{name}.monthly_contribution_eur must be a number."
            )
        if contribution < 0:
            raise ProfileConfigError(
                f"profiles.{name}.monthly_contribution_eur cannot be negative."
            )

        profiles[name] = Profile(
            name=name,
            telegram_id=telegram_id,
            root=roots / name,
            operator=operator,
            enabled=enabled,
            monthly_contribution_eur=float(contribution),
            base_currency=str(values.get("base_currency", "EUR")),
        )

    operators = [profile for profile in profiles.values() if profile.operator]
    if len(operators) > 1:
        raise ProfileConfigError(
            f"{path} marks {len(operators)} profiles as operator; exactly one "
            f"may be, since it is the default for bare commands."
        )
    if not operators:
        raise ProfileConfigError(
            f"{path} has no operator profile. Mark one with 'operator = true' "
            f"so commands without --profile know whom to act for."
        )
    return profiles


def operator_profile(profiles: dict[str, Profile]) -> Profile:
    """Return the operator profile, used when no --profile is given.

    Args:
        profiles: The loaded roster.

    Returns:
        The single profile marked as operator.

    Raises:
        ProfileConfigError: If no profile is marked operator.
    """
    for profile in profiles.values():
        if profile.operator:
            return profile
    raise ProfileConfigError("The roster has no operator profile.")


def resolve_cli_profile(
    name: str | None,
    *,
    db: str | None = None,
    roster_path: Path = PROFILES_FILE,
    require_existing: bool = True,
) -> tuple[Profile | None, Path]:
    """Resolve which database a command should act on.

    An explicit ``--db`` wins and returns no profile, which is the escape hatch
    for an experimental database. Otherwise the named profile is used, or the
    operator profile when none is named.

    Args:
        name: Profile name from ``--profile``, or None.
        db: Explicit database path from ``--db``, or None.
        roster_path: Roster file to read.
        require_existing: Refuse to return a path that does not exist. Commands
            that create a database pass False.

    Returns:
        ``(profile or None, database path)``.

    Raises:
        ProfileConfigError: If the profile or database is unknown or missing.
    """
    if db:
        db_path = Path(db).expanduser().resolve()
        if require_existing and not db_path.exists():
            raise ProfileConfigError(
                f"Database does not exist: {db_path}. Run 'main.py init' to "
                f"create one; no command creates a database implicitly."
            )
        return None, db_path

    profiles = load_profiles(roster_path)
    if name:
        try:
            profile = profiles[name]
        except KeyError as exc:
            known = ", ".join(sorted(profiles)) or "none"
            raise ProfileConfigError(
                f"Unknown profile {name!r} in {roster_path}. Known: {known}."
            ) from exc
    else:
        profile = operator_profile(profiles)

    if require_existing and not profile.db.exists():
        raise ProfileConfigError(
            f"No database for profile {profile.name!r} at {profile.db}. Run "
            f"'uv run python main.py init --profile {profile.name}'."
        )
    return profile, profile.db


def _context_template(file: ContextFile, profile_name: str) -> str:
    """Return the starter content for one context file."""
    if file.generated:
        return (
            f"{_STUB_MARKER}\n\n# {file.title}\n\n"
            f"{file.purpose}\n\n"
            f"CashAsh writes this file. Anything you add here will be "
            f"overwritten.\n"
        )
    return (
        f"{_STUB_MARKER}\n\n# {file.title}\n\n"
        f"> {file.purpose}\n>\n"
        f"> Replace this whole block with your own words. Until you do, "
        f"CashAsh treats the file as empty and will say so in "
        f"`main.py context`.\n\n"
        f"_Profile: {profile_name}_\n"
    )


def add_profile(
    name: str,
    telegram_id: int,
    *,
    operator: bool = False,
    monthly_contribution_eur: float = DEFAULT_MONTHLY_CONTRIBUTION_EUR,
    roster_path: Path = PROFILES_FILE,
) -> Profile:
    """Create a profile, its directories, and its context file templates.

    Args:
        name: Profile name; becomes a directory name.
        telegram_id: Numeric Telegram user id the bot routes by.
        operator: Whether this is the default profile for bare commands.
        monthly_contribution_eur: Planning figure for new money.
        roster_path: Roster file to append to.

    Returns:
        The created profile.

    Raises:
        ProfileConfigError: If the name or Telegram id is taken, if the first
            profile is not an operator, or if a second operator is requested.
    """
    validate_profile_name(name)
    if telegram_id <= 0:
        raise ProfileConfigError("Telegram ID must be a positive integer.")

    existing: dict[str, Profile] = {}
    if roster_path.exists():
        try:
            existing = load_profiles(roster_path)
        except ProfileConfigError:
            # A roster that fails validation must not be silently appended to.
            raise

    if name in existing:
        raise ProfileConfigError(f"Profile {name!r} already exists.")
    if any(profile.telegram_id == telegram_id for profile in existing.values()):
        raise ProfileConfigError(f"Telegram ID {telegram_id} is already assigned.")
    if existing and operator:
        raise ProfileConfigError(
            "The roster already has an operator profile. Only one profile may "
            "be the default for bare commands."
        )
    if not existing and not operator:
        raise ProfileConfigError(
            "The first profile must be the operator; pass --operator. It is "
            "what commands without --profile act on."
        )

    root = PROFILES_DIR / name
    if root.exists():
        raise ProfileConfigError(
            f"Profile directory already exists: {root}. Remove it or choose "
            f"another name."
        )

    profile = Profile(
        name=name,
        telegram_id=telegram_id,
        root=root,
        operator=operator,
        monthly_contribution_eur=monthly_contribution_eur,
    )
    profile.context.mkdir(parents=True, exist_ok=True)
    for file in CONTEXT_FILES:
        profile.context_path(file.name).write_text(
            _context_template(file, name), encoding="utf-8"
        )

    roster_path.parent.mkdir(parents=True, exist_ok=True)
    header = "" if roster_path.exists() else "# CashAsh profile roster.\n"
    with roster_path.open("a", encoding="utf-8") as handle:
        handle.write(
            f"{header}\n[profiles.{name}]\n"
            f"telegram_id = {telegram_id}\n"
            f"operator = {str(operator).lower()}\n"
            f"enabled = true\n"
            f"monthly_contribution_eur = {monthly_contribution_eur}\n"
        )
    logger.info("Created profile %s at %s", name, root)
    return profile


def is_stub(path: Path) -> bool:
    """Return True when a context file is still the untouched template."""
    if not path.exists():
        return False
    try:
        return _STUB_MARKER in path.read_text(encoding="utf-8")
    except OSError:
        return False


def context_status(profile: Profile) -> list[tuple[ContextFile, str]]:
    """Return each context file with its status.

    Args:
        profile: Profile to inspect.

    Returns:
        ``(file, status)`` pairs where status is ``written``, ``template`` or
        ``missing``.
    """
    result: list[tuple[ContextFile, str]] = []
    for file in CONTEXT_FILES:
        path = profile.context_path(file.name)
        if not path.exists():
            status = "missing"
        elif is_stub(path):
            status = "template"
        else:
            status = "written"
        result.append((file, status))
    return result
